#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: bnp-demo
  namespace: #@ data.values.namespace
type: Opaque
stringData:
  db-url: #@ data.values.db_url
  db-username: #@ data.values.db_username
  db-password: #@ data.values.db_password
